[package]
name = "frontend"
version = "0.1.0"
authors = ["Ibrahim <ibrahim.haji.3595@gmail.com>"]
edition = "2021"
repository = "https://github.com/ibrahim-3595/Secure-Journal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = ["web", "router"] }
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
async-std = "1"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
