[package]
name = "frontend"
version = "0.1.0"
authors = ["Ibrahim <ibrahim.haji.3595@gmail.com>"]
edition = "2021"
repository = "https://github.com/ibrahim-3595/Secure-Journal"

[dependencies]
dioxus = { version = "0.7.1", features = ["router"] }
serde = { version = "1", features = ["derive"] }
async-std = "1"

# Desktop-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus = { version = "0.7.1", features = ["desktop", "router"] }
reqwest = { version = "0.12", features = ["json"] }

# Web-only dependencies  
[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { version = "0.7.1", features = ["web", "router"] }
reqwest = { version = "0.12", default-features = false, features = ["json"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1