[application]
name = "secure_journal"
default_platform = "web"

[web.app]
title = "Secure Journal"

[web.asset]
# Copy this folder to /dist/assets/
include = ["assets"]

[web.resource]
# Tell Dioxus to inject these files into <head>
style = ["/assets/main.css", "/assets/tailwind.css"]
script = []

[web.resource.dev]
script = []
